# Generated by Django 5.1.7 on 2025-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
